name: Trivy Scan

on:
  push:
    branches:
      - Staging

jobs:
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy scan
        run: |
          docker run --rm -v $PWD:/target aquasec/trivy --severity HIGH,CRITICAL /target:Staging

