name: Trivy Scan

on:
  push:
    branches:
      - Staging

jobs:
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v1
        with:
          image-ref: docker.io/aquasec/trivy:latest

      - name: Run Trivy scan
        run: |
          trivy --exit-code 1 --severity HIGH,CRITICAL Staging
